### ISSUE TITLE
[TASK] Default leaf in Merkle Tree

### ISSUE THREAD

**Issue by drewstone** [webb-tools/arkworks-gadgets#105]
Hash empty of merkle tree defaults to zero element. In the Solidity side, the default empty element is not zero, but rather than keccak256("tornado") or something similar. We should allow this element to be configurable in Rust as well.

https://github.com/webb-tools/arkworks-gadgets/blob/master/arkworks-gadgets/src/merkle_tree/mod.rs#L373

**Comment by filiplazovic** [comment]
It will be done in #106
