### ISSUE TITLE
[TASK] Returning structs instead of tuples on setup functions

### ISSUE THREAD

**Issue by drewstone** [webb-tools/arkworks-gadgets#125]

**Comment by OAyomide** [comment]
I'd love to take this ticket (seems like a good entry to the repo) but I cannot find the setup directory. perhaps this issue can be updated to reflect this?

**Comment by drewstone** [comment]
What do you mean by a setup directory? @OAyomide

Agree that this could be a good first issue, naming of the struct parameters would require some understanding but we welcome contributions. Feel free to ask questions or write up some specification ideas.
