### ISSUE TITLE
[TASK] Improve dependency graph + workspace structure

### ISSUE THREAD

**Issue by filiplazovic** [webb-tools/arkworks-gadgets#131]
# 1. Structure
We should have a workspace with the following structure:
- [`arkworks-benchmarks`](https://github.com/webb-tools/arkworks-gadgets/tree/master/arkworks-benchmarks)
- [`arkworks-circom-verifier`](https://github.com/webb-tools/arkworks-gadgets/tree/master/arkworks-circom-verifier)
- `arkworks-r1cs-circuits` - which contains only the r1cs constraints version of our circuits + gadgets
- `arkworks-setups` - contains the higher level APIs for both R1CS and PLONK circuits
- `arkworks-native-circuits` - which contains only the native version of our gadgets
- [`arkworks-plonk-circuits`](https://github.com/webb-tools/arkworks-gadgets/tree/master/arkworks-plonk-circuits)
- [`arkworks-utils`](https://github.com/webb-tools/arkworks-gadgets/tree/master/arkworks-utils)

# 2. Tools
Use [cargo-workspaces](https://github.com/pksunkara/cargo-workspaces) for workspace publishing.

# 3. Dependency graph

1. `arkworks-gadgets` should not have dependency of `arkworks-utils`, except for testing.
2. Move `PoseidonParameters`, `Sbox`, `PoseidonError` (https://github.com/webb-tools/arkworks-gadgets/blob/master/arkworks-utils/src/poseidon/mod.rs) into the `arkworks-native-circuits/poseidon` directory.
    - Types related to the native version goes to `arkworks-native-circuits`.
    - r1cs constraints version for sbox goes to `arkworks-r1cs-circuits`, etc.
3. Modify utility functions for Poseidon to not return PoseidonParameters struct, but instead return tuple:
```rust
(Vec<F>, Vec<Vec<F>>, u8, u8, u8, PoseidonSbox)
```
4. Move `setup_params...`(https://github.com/webb-tools/arkworks-gadgets/blob/master/arkworks-utils/src/utils/common.rs#L23) functions inside the native version of poseidon.

5. Elliptic curves should only be imported for testing, for all crates.

**Comment by filiplazovic** [comment]
@drewstone Let me know what you think. We could also break `arkworks-r1cs-circuits` and `arkworks-plonk-circuits` into two parts: `arkworks-[x]-circuits + arkworks-[x]-gadgets`

**Comment by drewstone** [comment]
This looks good

**Comment by drewstone** [comment]
We would need updates to the documentation as well @filiplazovic. Perhaps we can add to this proper rust docs and start publishing this online.
