### ISSUE TITLE
[TASK] Properly handle public, private and constant inputs to the PLONK circuit

### ISSUE THREAD

**Issue by GhostOfGauss** [webb-tools/arkworks-gadgets#147]
The way that Poseidon hash parameters are [currently](https://github.com/webb-tools/arkworks-gadgets/blob/e56b053053bdccf36b12635d28b65f8985eaddd4/arkworks-plonk-circuits/src/poseidon/poseidon.rs#L53-L66) added to a hash gadget using `add_input`, which treats them as secret inputs rather than public constants.  Thus a verifier cannot be certain that the prover used the correct constants to compute their hash.  This qualifies as a bug b/c a prover could choose trivial parameters (like MDS matrix = identity, all round constants = 0) and more easily find hash preimages.

I believe the best way to fix this is to use `add_witness_to_circuit_description` because this method of creating variables makes the variable's underlying value visible to the verifier.  Thus the verifier can be certain that the correct poseidon parameters were used in generating the hash proof.  I would like confirmation from plonk experts at ZK garage before fixing this.

**Comment by GhostOfGauss** [comment]
To elaborate on why `add_witness_to_circuit_description` seems correct:

This consists of two calls ([see here](https://github.com/ZK-Garage/plonk/blob/b839b0e1c326a770ca641dd5129ed40dc18794dd/plonk-core/src/constraint_system/composer.rs#L173-L179)): 

*   `add_input` to add a new variable to the composer
*   `constrain_to_constant` to demonstrate that the variable was added with a given value.  This step reveals the value to the verifier.

The `constrain_to_constant` method is appropriate when the constant argument is truly constant across all instances of the circuit ([see here](https://github.com/ZK-Garage/plonk/blob/b839b0e1c326a770ca641dd5129ed40dc18794dd/plonk-core/src/constraint_system/composer.rs#L294-L298)).  So things like hash function parameters qualify as constant, whereas things like the publicly visible hash output we wish to prove pre-image knowledge of would not qualify as constant b/c this is different in each instance of the circuit.

**Comment by filiplazovic** [comment]
Ok, summery of our chat:
1. For private inputs: Use `add_input`
2. For public inputs: Use custom poly_gate function:
```rust
composer.poly_gate(
    a,
    a,
    a,
    F::zero(),
    -F::one(),
    F::zero(),
    F::zero(),
    F::zero(),
    Some(passed_a),
);
```
Where `a` is the variable already in the circuit, and `passed_a` is the value passed from outside world.
3. For constants: Use `add_witness_to_circuit_description`

The plan for implementing this:
- Modify `from_native` function for Poseidon. Instead of `add_inputs`, use `add_witness_to_circuit_description`, since we are dealing with constants.
- Add a function inside the `MixerCircuit` called `add_public_input` for handling public inputs
