### ISSUE TITLE
[SPEC] is_eq gadget

### ISSUE THREAD

**Issue by drewstone** [webb-tools/arkworks-gadgets#76]
The basic equation goes like this:
```rust
let b = 1 - x * x_inverse;
assert(b * x, 0);
```
Where:
`x` is the number we want to check.
`x_inverse` is the inverse of `x` (meaning `x * x_inverse == 1`).
`b` is the boolean value indicating if `x` is `0`.

Here is the gadget example:
```rust
#[derive(Debug, Default)]
struct IsZero<E: PairingEngine> {
	pub x: E::Fr,
	pub x_inv: E::Fr,
}

impl<E: PairingEngine, P: TEModelParameters<BaseField = E::Fr>> Circuit<E, P> for IsZero<E> {
	const CIRCUIT_ID: [u8; 32] = [0xff; 32];

	fn gadget(&mut self, composer: &mut StandardComposer<E, P>) -> Result<(), Error> {
		let x_var = composer.add_input(self.x);
		let x_inv_var = composer.add_input(self.x_inv);
		let one = composer.add_input(E::Fr::one());

		// x * x_inverse
		// -- should be 1 if x != 0
		// -- should be 0 if x == 0
		let res =
			composer.arithmetic_gate(|gate| gate.witness(x_var, x_inv_var, None).mul(E::Fr::one()));

		// b = 1 - x * x_inverse
		// will be 0 if x != 0
		// will be 1 if x == 0
		let b = composer.arithmetic_gate(|gate| {
			gate.witness(one, res, None)
				.add(E::Fr::one(), -E::Fr::one())
		});

		// ensures that x_inv is actually the inverse of x
		let b_check =
			composer.arithmetic_gate(|gate| gate.witness(x_var, b, None).mul(E::Fr::one()));
		composer.assert_equal(b_check, composer.zero_var());

		// If x is 0, b should be 1
		// If x is 1, b should be zero
		composer.assert_equal(b, one);

		Ok(())
	}

	fn padded_circuit_size(&self) -> usize {
		1 << 11
	}
}
```
The full code can be found here: https://github.com/webb-tools/arkworks-gadgets/blob/filip/iz-zero-gadget/arkworks-plonk-circuits/src/utils.rs

**Comment by GhostOfGauss** [comment]
# Overview

**Comment by filiplazovic** [comment]
@GhostOfGauss I added a gadget example in the description, although it's not working properly yet.

To avoid having to pass `x_inverse` into the circuit, it's best to add this change directly into the ark-plonk library, since from the inside you have the access to the values of the variables, so you can calculate the inverse easily. Example: https://github.com/ZK-Garage/plonk/blob/master/src/constraint_system/ecc/curve_addition/variable_base_gate.rs#L166-L172

**Comment by GhostOfGauss** [comment]
I've added an `is-nonzero-gate` that outputs a variable whose 0 if its input is 0 and 1 otherwise.  This seems to do the job.  Could you please check here to see what you think? https://github.com/webb-tools/ark-plonk/blob/todd/is-eq-gate/src/constraint_system/boolean.rs

**Comment by GhostOfGauss** [comment]
I've opened a PR webb-tools/ark-plonk#1

**Comment by GhostOfGauss** [comment]
PR ZK-Garage/plonk#77 has been merged and resolves this issue.
